version: "3.6"
services:
  nginx:
    container_name: nginx-${NGINX_VERSION}
    build:
      context: ./nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_VHOST_PATH}:/etc/nginx/conf.d
      - ${NGINX_LOG_PATH}:/data/logs/nginx
      - ${WEB_ROOT_PATH}:/var/www
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    container_name: php-pfm-${PHP_VERSION}
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_PCNTL=${PHP_INSTALL_PCNTL}
        - INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE}
        - INSTALL_MSGPACK=${PHP_INSTALL_MSGPACK}
        - INSTALL_MSGPACK_VERSION=${PHP_INSTALL_MSGPACK_VERSION}
        - INSTALL_IGBINARY=${PHP_INSTALL_IGBINARY}
        - INSTALL_IGBINARY_VERSION=${PHP_INSTALL_IGBINARY_VERSION}
        - INSTALL_REDIS=${PHP_INSTALL_REDIS}
        - INSTALL_REDIS_VERSION=${PHP_INSTALL_REDIS_VERSION}
        - INSTALL_MONGODB=${PHP_INSTALL_MONGODB}
        - INSTALL_MONGODB_VERSION=${PHP_INSTALL_MONGODB_VERSION}
        - INSTALL_MEMCACHED=${PHP_INSTALL_MEMCACHED}
        - INSTALL_MEMCACHED_VERSION=${PHP_INSTALL_MEMCACHED_VERSION}
        - INSTALL_SWOOLE=${PHP_INSTALL_SWOOLE}
        - INSTALL_SWOOLE_VERSION=${PHP_INSTALL_SWOOLE_VERSION}
        - INSTALL_YACONF=${PHP_INSTALL_YACONF}
        - INSTALL_YACONF_VERSION=${PHP_INSTALL_YACONF_VERSION}
        - INSTALL_YAF=${PHP_INSTALL_YAF}
        - INSTALL_YAF_VERSION=${PHP_INSTALL_YAF_VERSION}
        - INSTALL_SEASLOG=${PHP_INSTALL_SEASLOG}
        - INSTALL_SEASLOG_VERSION=${PHP_INSTALL_SEASLOG_VERSION}
        - INSTALL_ZIP=${PHP_INSTALL_ZIP}
        - INSTALL_ZIP_VERSION=${PHP_INSTALL_ZIP_VERSION}
        - INSTALL_YAML=${PHP_INSTALL_YAML}
        - INSTALL_YAML_VERSION=${PHP_INSTALL_YAML_VERSION}
        - INSTALL_AMQP=${PHP_INSTALL_AMQP}
        - INSTALL_AMQP_VERSION=${PHP_INSTALL_AMQP_VERSION}
        - INSTALL_XUNSEARCH=${PHP_INSTALL_XUNSEARCH}
        - INSTALL_COMPOSER=${PHP_INSTALL_COMPOSER}
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - "${PHP_CONF_PATH}-${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini"
      - "${PHP_CONF_PATH}-${PHP_VERSION}/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "${PHP_CONF_PATH}-${PHP_VERSION}/php-fpm.d:/usr/local/etc/php-fpm.d"
      - ${WEB_ROOT_PATH}:/var/www

  mysql:
    container_name: mysql-${MYSQL_VERSION}
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mongo:
    container_name: mongo-${MONGO_VERSION}
    build:
      context: ./mongo
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  redis:
    container_name: redis-${REDIS_VERSION}
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data"
    restart: always

  memcached:
    container_name: memcached-${MEMCACHED_VERSION}
    build:
      context: ./memcached
      args:
        - MEMCACHED_VERSION=${MEMCACHED_VERSION}
    ports:
      - ${MEMCACHED_PORT}:11211