version: "3.6"
services:
  redis:
    container_name: redis-${REDIS_VERSION}
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data"
    restart: always

  memcached:
    container_name: memcached-${MEMCACHED_VERSION}
    build:
      context: ./memcached
      args:
        - MEMCACHED_VERSION=${MEMCACHED_VERSION}
    ports:
      - ${MEMCACHED_PORT}:11211
  

